name: Sync with own cdn

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sync:
    environment:
      name: cdn-main
      url: https://cdn.investigativedata.org/style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git*'
        env:
          AWS_S3_BUCKET: cdn.investigativedata.org
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
          AWS_REGION: "eu-central-1"
          DEST_DIR: "style"
